import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by next-pwa at build time.
    "public/sw.js",
    "public/workbox-*.js",
    // Bundled skill assets, not app code.
    ".claude/**",
    ".agents/**",
    ".windsurf/**",
  ]),
]);

export default eslintConfig;
